import React from 'react'

import withPost from 'nextein/post'

const Recap = () => {
    return(
        <div class="wrapper">
            <title>Recap</title>
            <div class="row"> 
                <img src="static/img/ChickenMumbo_LogoWords.png" class="cash"/>
                {/* <div class="row">
                    <div class="lineup">4-11-19 @ BIG CHIEF</div><br></br>
                </div>  */}
                <div class="row">
                    <div class="lineup">PHOTOS BY<a class="instalink" href="http://www.instagram.com/africanist">@AFRICANIST</a></div><br></br>
                </div>
                <img src="static/img/930-recap/IMG_8297.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8489.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8000.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9294.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9265.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4337.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9430.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8872.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8005.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8141.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9024.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8921.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8164.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9261.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8132.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9048.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8726.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8414.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8072.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8097.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8551.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9268.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9563.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8486.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9495.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9262.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8881.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4319.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8908.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8518.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8968.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7894.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8239.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9305.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9527.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8931.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9570.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8348.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8275.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8076.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8523.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4327.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8220.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8281.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8832.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7886.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8500.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7959.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8508.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8496.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4326.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8748.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8741.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8150.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7916.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4333.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9468.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8017.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8808.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7957.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8738.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9470.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9143.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8083.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9149.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7944.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9049.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9132.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8598.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7885.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8521.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8254.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9082.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7873.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9491.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8444.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8898.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8277.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7876.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9296.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8347.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8941.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4336.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8247.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8977.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8295.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8875.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9025.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9490.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8958.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9239.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8305.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8104.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8007.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7963.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8935.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9501.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8645.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9290.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8753.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8419.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8166.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8923.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8644.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7995.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8983.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7927.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4331.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8155.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8493.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8106.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7893.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8259.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8543.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8664.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7955.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8877.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7964.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8130.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8378.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7908.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8352.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8225.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8283.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8163.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8345.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8146.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8663.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4334.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8241.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7991.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8937.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8595.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8635.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7871.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8467.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8372.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8643.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8398.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8101.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8356.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8634.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7854.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8990.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8214.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8661.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7989.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9139.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8111.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9471.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9319.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8549.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8588.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8216.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7960.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8358.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8367.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9474.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9379.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7982.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8285.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9263.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8803.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8255.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8109.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8053.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8370.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7953.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8580.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8287.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9293.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8233.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9446.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8145.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8223.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9494.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8599.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8749.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9274.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8417.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9427.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8943.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8099.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9084.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8490.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8680.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7892.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8253.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8289.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8258.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8349.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8993.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8767.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9115.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8068.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7912.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8014.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7866.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8121.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8555.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8473.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8012.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9042.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7872.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7923.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9473.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8498.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7961.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8235.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8564.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8702.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8533.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7985.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8013.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8401.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7951.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7880.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8056.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9572.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8075.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9234.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9278.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9500.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8117.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8404.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8476.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8743.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8527.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8548.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8279.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8930.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7943.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8705.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8219.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9164.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7925.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8796.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9428.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7896.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8380.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9264.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8227.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8309.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9310.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7905.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9081.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8894.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8418.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8936.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8341.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7950.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8011.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8967.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7858.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8618.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9307.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9356.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8572.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8999.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7965.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8888.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9297.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8554.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8136.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8333.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9279.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8944.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8413.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8222.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9116.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8172.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7909.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8885.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8525.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8403.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8231.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4332.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8515.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8079.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9030.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8677.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9562.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8568.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9117.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9273.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8081.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8237.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9114.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9211.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7910.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7940.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8791.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7997.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8681.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4335.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9311.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9072.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9308.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8243.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8169.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8165.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8929.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8817.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8546.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8319.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9330.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8807.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8368.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9289.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8596.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8262.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8981.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8112.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8485.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8745.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8020.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8168.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8343.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7906.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8212.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8116.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8139.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8228.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8994.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9080.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8415.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8905.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8688.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8974.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7917.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8582.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8904.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8337.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8924.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9235.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9448.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7936.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7987.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7978.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8015.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4329.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9170.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8010.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7932.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8127.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8143.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7914.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9517.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8078.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9236.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9478.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8320.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8315.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9126.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7922.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8029.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8874.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7984.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7904.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_7903.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8001.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_4330.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9141.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8338.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8772.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_8942.jpg" class="recap" />
                    <img src="static/img/930-recap/IMG_9212.jpg" class="recap" />
            </div>
         </div>
    )
    
}
export default Recap;
