import React from 'react';
import Footer from '../components/Footer';
import Navigation from '../components/Navigation';
import withPost from 'nextein/post';

const Recap = () => {
  return (
    <div class="wrapper">
      <title>Recap</title>
      <Navigation />
      <div class="row">
        <img src="static/img/logocrank.png" class="cash" />
        {/* <div class="row">
                    <div class="lineup">9-13-19 @ 9:30 CLUB</div><br></br>
                </div>  */}
        <div class="row">
          <div class="lineup">
            PHOTOS BY{' '}
            <a class="instalink" href="http://www.instagram.com/thatmanztyy">
              @THATMANZTYY
            </a>{' '}
            +{' '}
            <a class="instalink" href="http://www.instagram.com/jadaimanim">
              @JADAIMANIM
            </a>
          </div>
          <br></br>
        </div>
        <img
          src="static/img/jada-crank2-compressed/700A0396.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0384.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0260.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0277.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0229.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0451.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0522.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0642.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0327.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0235.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0230.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0187.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0349.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0239.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0482.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0167.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0639.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0265.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0572.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0253.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0515.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0345.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0603.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0322.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0564.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0195.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0232.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0532.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0607.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0386.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0513.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0554.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0471.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0596.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0348.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0625.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0611.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0436.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0478.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0180.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0185.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0186.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0174.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0233.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0622.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0135.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0601.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0151.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0330.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0584.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0462.jpg"
          class="recap"
        />

        <img
          src="static/img/jada-crank2-compressed/700A0240.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1277jpg_48752605352_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0347.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0530.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1512jpg_48762088806_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1519jpg_48762090396_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0499.jpg"
          class="recap"
        />

        <img
          src="static/img/josef-crank-compressed/img_1037jpg_48740782096_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0529.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0237.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1157jpg_48752378846_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1011jpg_48740965142_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0215.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1069jpg_48740970147_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1177jpg_48752572302_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0923jpg_48740960492_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0847jpg_48740772276_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0502.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0383.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1046jpg_48740455113_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1582jpg_48761775913_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1467jpg_48762087541_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1139jpg_48740975932_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1562jpg_48762279337_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0619.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1465jpg_48762274607_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0318.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0505.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0208.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0487.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1062jpg_48740457288_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1218jpg_48752073463_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1284jpg_48752095143_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1125jpg_48740463023_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0313.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1577jpg_48762279972_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0374.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1461jpg_48762273757_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0498.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0583.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0527.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0190.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0408.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0287.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1355jpg_48752235313_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0950jpg_48740448033_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0389.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0343.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0334.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1393jpg_48752754712_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0286.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0594.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0131.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1213jpg_48752072008_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0244.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1428jpg_48761767303_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0857jpg_48740957802_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0225.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0403.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0145.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0172.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0181.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0171.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1146jpg_48740976327_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0364.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0241.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0909jpg_48740774496_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0143.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0246.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1506jpg_48762088011_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0342.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0420.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0147.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0984jpg_48740778716_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0375.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1337jpg_48752558726_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1086jpg_48740970767_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1122jpg_48740790001_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1099jpg_48740460388_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0362.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1110jpg_48740788816_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1273jpg_48752090003_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1033jpg_48740453718_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1509jpg_48761771013_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1247jpg_48752083393_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1266jpg_48752601927_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1288jpg_48752096248_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0915jpg_48740774886_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0547.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0257.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1095jpg_48740460023_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1434jpg_48762085016_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0881jpg_48740445653_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0987jpg_48740451198_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0405.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0221.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0496.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1159jpg_48752568672_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1208jpg_48752394926_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1328jpg_48752745137_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1349jpg_48752231498_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1004jpg_48740964852_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1108jpg_48740460923_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0474.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0574.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1411jpg_48762271342_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0326.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0563.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1383jpg_48752236993_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1299jpg_48752739197_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0392.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0429.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1243jpg_48752597632_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1203jpg_48752391026_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0394.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1270jpg_48752414126_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0585.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0970jpg_48740962842_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0961jpg_48740448983_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0382.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1451jpg_48762272942_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1052jpg_48740968067_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1317jpg_48752227618_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1112jpg_48740789156_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0874jpg_48740958157_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0447.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1199jpg_48752058123_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1373jpg_48752236638_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1219jpg_48752077418_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0581.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0139.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0138.jpg"
          class="recap"
        />

        <img
          src="static/img/josef-crank-compressed/img_1396jpg_48761765703_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1132jpg_48740975612_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1547jpg_48761773883_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1114jpg_48740789506_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1236jpg_48752593557_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1557jpg_48761774163_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1343jpg_48752231083_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0958jpg_48740961482_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1525jpg_48762278327_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0629.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0346.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0459.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1092jpg_48740459043_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_0982jpg_48740778311_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0295.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0251.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1182jpg_48752384601_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1567jpg_48762092001_o.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0360.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0352.jpg"
          class="recap"
        />
        <img
          src="static/img/jada-crank2-compressed/700A0494.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1543jpg_48762278577_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1402jpg_48761766203_o.jpg"
          class="recap"
        />
        <img
          src="static/img/josef-crank-compressed/img_1263jpg_48752410861_o.jpg"
          class="recap"
        />

        <Footer />
      </div>
    </div>
  );
};
export default Recap;
