import React from 'react'

import withPost from 'nextein/post'

export default withPost( ({ post }) => { 
    return(
        <div class="wrapper">
            <div class="row"> 
                <img src="static/img/logocrank.png" class="cash"/>
                {/* <div class="row">
                    <div class="lineup">4-11-19 @ BIG CHIEF</div><br></br>
                </div>  */}
                <div class="row">
                    <div class="lineup">PHOTOS BY @GETBOXED_</div><br></br>
                </div>               
                <img src="static/recap/DSC_0157.jpg" class="recap"/>
                <img src="static/recap/DSC_9990.jpg" class="recap"/>
                <img src="static/recap/DSC_9942.jpg" class="recap"/>
                <img src="static/recap/DSC_0155.jpg" class="recap"/>
                <img src="static/recap/DSC_0078.jpg" class="recap"/>
                <img src="static/recap/DSC_0132.jpg" class="recap"/>
                <img src="static/recap/DSC_0027.jpg" class="recap"/>
                <img src="static/recap/DSC_0238.jpg" class="recap"/>
                <img src="static/recap/DSC_0076.jpg" class="recap"/>
                <img src="static/recap/DSC_9796.jpg" class="recap"/>
                <img src="static/recap/DSC_9757.jpg" class="recap"/>
                <img src="static/recap/DSC_9918.jpg" class="recap"/>
                <img src="static/recap/DSC_9835.jpg" class="recap"/>
                <img src="static/recap/DSC_0172.jpg" class="recap"/>
                <img src="static/recap/DSC_0110.jpg" class="recap"/>
                <img src="static/recap/DSC_9988.jpg" class="recap"/>
                <img src="static/recap/DSC_0203.jpg" class="recap"/>
                <img src="static/recap/DSC_9956.jpg" class="recap"/>
                <img src="static/recap/DSC_9872.jpg" class="recap"/>
                <img src="static/recap/DSC_0164.jpg" class="recap"/>
                <img src="static/recap/DSC_0037.jpg" class="recap"/>
                <img src="static/recap/DSC_0134.jpg" class="recap"/>
                <img src="static/recap/DSC_9870.jpg" class="recap"/>
                <img src="static/recap/DSC_9774.jpg" class="recap"/>
                <img src="static/recap/DSC_9943.jpg" class="recap"/>
                <img src="static/recap/DSC_9935.jpg" class="recap"/>
                <img src="static/recap/DSC_0257.jpg" class="recap"/>
                <img src="static/recap/DSC_0010.jpg" class="recap"/>
                <img src="static/recap/DSC_0014.jpg" class="recap"/>
                <img src="static/recap/DSC_0059.jpg" class="recap"/>
                <img src="static/recap/DSC_0018.jpg" class="recap"/>
                <img src="static/recap/DSC_0160.jpg" class="recap"/>
                <img src="static/recap/DSC_0168.jpg" class="recap"/>
                <img src="static/recap/DSC_9914.jpg" class="recap"/>
                <img src="static/recap/DSC_0149.jpg" class="recap"/>
                <img src="static/recap/DSC_0147.jpg" class="recap"/>
                <img src="static/recap/DSC_0159.jpg" class="recap"/>
                <img src="static/recap/DSC_0270.jpg" class="recap"/>
                <img src="static/recap/DSC_0034.jpg" class="recap"/>
                <img src="static/recap/DSC_9985.jpg" class="recap"/>
                <img src="static/recap/DSC_0046.jpg" class="recap"/>
                <img src="static/recap/DSC_9964.jpg" class="recap"/>
                <img src="static/recap/DSC_0048.jpg" class="recap"/>
                <img src="static/recap/DSC_0225.jpg" class="recap"/>
                <img src="static/recap/DSC_9799.jpg" class="recap"/>
                <img src="static/recap/DSC_9860.jpg" class="recap"/>
                <img src="static/recap/DSC_0047.jpg" class="recap"/>
                <img src="static/recap/DSC_9896.jpg" class="recap"/>
                <img src="static/recap/DSC_0240.jpg" class="recap"/>
                <img src="static/recap/DSC_0008.jpg" class="recap"/>
                <img src="static/recap/DSC_9957.jpg" class="recap"/>
                <img src="static/recap/DSC_9915.jpg" class="recap"/>
                <img src="static/recap/DSC_9899.jpg" class="recap"/>
                <img src="static/recap/DSC_0026.jpg" class="recap"/>
                <img src="static/recap/DSC_9878.jpg" class="recap"/>
                <img src="static/recap/DSC_0126.jpg" class="recap"/>
                <img src="static/recap/DSC_9777.jpg" class="recap"/>
                <img src="static/recap/DSC_9954.jpg" class="recap"/>
                <img src="static/recap/DSC_9811.jpg" class="recap"/>
                <img src="static/recap/DSC_0135.jpg" class="recap"/>
                <img src="static/recap/DSC_0158.jpg" class="recap"/>
                <img src="static/recap/DSC_0190.jpg" class="recap"/>
                <img src="static/recap/DSC_0248.jpg" class="recap"/>
                <img src="static/recap/DSC_0129.jpg" class="recap"/>
                <img src="static/recap/DSC_0187.jpg" class="recap"/>
                <img src="static/recap/DSC_9997.jpg" class="recap"/>
                <img src="static/recap/DSC_9769.jpg" class="recap"/>
                <img src="static/recap/DSC_0236.jpg" class="recap"/>
                <img src="static/recap/DSC_9968.jpg" class="recap"/>
                <img src="static/recap/DSC_9767.jpg" class="recap"/>
                <img src="static/recap/DSC_0124.jpg" class="recap"/>
                <img src="static/recap/DSC_0062.jpg" class="recap"/>
                <img src="static/recap/DSC_9886.jpg" class="recap"/>
                <img src="static/recap/DSC_0006.jpg" class="recap"/>
                <img src="static/recap/DSC_9912.jpg" class="recap"/>
                <img src="static/recap/DSC_0072.jpg" class="recap"/>
                <img src="static/recap/DSC_0261.jpg" class="recap"/>
                <img src="static/recap/DSC_9884.jpg" class="recap"/>
                <img src="static/recap/DSC_9864.jpg" class="recap"/>
                <img src="static/recap/DSC_0128.jpg" class="recap"/>
                <img src="static/recap/DSC_0055.jpg" class="recap"/>
                <img src="static/recap/DSC_0191.jpg" class="recap"/>
                <img src="static/recap/DSC_0066.jpg" class="recap"/>
                <img src="static/recap/DSC_0213.jpg" class="recap"/>
                <img src="static/recap/DSC_9951.jpg" class="recap"/>
                <img src="static/recap/DSC_9931.jpg" class="recap"/>
                <img src="static/recap/DSC_0146.jpg" class="recap"/>
                <img src="static/recap/DSC_9776.jpg" class="recap"/>
                <img src="static/recap/DSC_0057.jpg" class="recap"/>
                <img src="static/recap/DSC_0054.jpg" class="recap"/>
                <img src="static/recap/DSC_0021.jpg" class="recap"/>
                <img src="static/recap/DSC_0051.jpg" class="recap"/>
                <img src="static/recap/DSC_9875.jpg" class="recap"/>
                <img src="static/recap/DSC_9817.jpg" class="recap"/>
                <img src="static/recap/DSC_0138.jpg" class="recap"/>
                <img src="static/recap/DSC_9877.jpg" class="recap"/>
                <img src="static/recap/DSC_9911.jpg" class="recap"/>
                <img src="static/recap/DSC_9825.jpg" class="recap"/>
                <img src="static/recap/DSC_9787.jpg" class="recap"/>
                <img src="static/recap/DSC_9828.jpg" class="recap"/>
                <img src="static/recap/DSC_9971.jpg" class="recap"/>
                <img src="static/recap/DSC_9761.jpg" class="recap"/>
                <img src="static/recap/DSC_0064.jpg" class="recap"/>
                <img src="static/recap/DSC_0020.jpg" class="recap"/>
                <img src="static/recap/DSC_9844.jpg" class="recap"/>
                <img src="static/recap/DSC_9819.jpg" class="recap"/>
                <img src="static/recap/DSC_9766.jpg" class="recap"/>
                <img src="static/recap/DSC_9888.jpg" class="recap"/>
                <img src="static/recap/DSC_9816.jpg" class="recap"/>
                <img src="static/recap/DSC_0043.jpg" class="recap"/>
                <img src="static/recap/DSC_9970.jpg" class="recap"/>
                <img src="static/recap/DSC_9778.jpg" class="recap"/>
                <img src="static/recap/DSC_0178.jpg" class="recap"/>
                <img src="static/recap/DSC_0023.jpg" class="recap"/>
                <img src="static/recap/DSC_9873.jpg" class="recap"/>
                <img src="static/recap/DSC_0224.jpg" class="recap"/>
                <img src="static/recap/DSC_9965.jpg" class="recap"/>
                <img src="static/recap/DSC_9961.jpg" class="recap"/>
                <img src="static/recap/DSC_9859.jpg" class="recap"/>
                <img src="static/recap/DSC_0194.jpg" class="recap"/>
                <img src="static/recap/DSC_0001.jpg" class="recap"/>
                <img src="static/recap/DSC_0001.jpg" class="recap"/>
                <img src="static/recap/DSC_9963.jpg" class="recap"/>
                <img src="static/recap/DSC_0163.jpg" class="recap"/>
                <img src="static/recap/DSC_9880.jpg" class="recap"/>
                <img src="static/recap/DSC_0067.jpg" class="recap"/>
                <img src="static/recap/DSC_9887.jpg" class="recap"/>
                <img src="static/recap/DSC_9882.jpg" class="recap"/>
                <img src="static/recap/DSC_0141.jpg" class="recap"/>
                <img src="static/recap/DSC_9791.jpg" class="recap"/>
                <img src="static/recap/DSC_0058.jpg" class="recap"/>
                <img src="static/recap/DSC_0231.jpg" class="recap"/>
                <img src="static/recap/DSC_9949.jpg" class="recap"/>
                <img src="static/recap/DSC_9959.jpg" class="recap"/>
                <img src="static/recap/DSC_9946.jpg" class="recap"/>
                <img src="static/recap/DSC_0002.jpg" class="recap"/>
                <img src="static/recap/DSC_0140.jpg" class="recap"/>
                <img src="static/recap/DSC_0019.jpg" class="recap"/>
                <img src="static/recap/DSC_0125.jpg" class="recap"/>
                <img src="static/recap/DSC_9923.jpg" class="recap"/>
                <img src="static/recap/DSC_0081.jpg" class="recap"/>
                <img src="static/recap/DSC_9895.jpg" class="recap"/>
                <img src="static/recap/DSC_9822.jpg" class="recap"/>
                <img src="static/recap/DSC_9830.jpg" class="recap"/>
                <img src="static/recap/DSC_9979.jpg" class="recap"/>
                <img src="static/recap/DSC_0144.jpg" class="recap"/>
                <img src="static/recap/DSC_9998.jpg" class="recap"/>            
                <img src="static/recap/DSC_9798.jpg" class="recap"/>
                <img src="static/recap/DSC_9849.jpg" class="recap"/>
                <img src="static/recap/DSC_0130.jpg" class="recap"/>
                <img src="static/recap/DSC_9937.jpg" class="recap"/>
                <img src="static/recap/DSC_9980.jpg" class="recap"/>
                <img src="static/recap/DSC_9953.jpg" class="recap"/>
                <img src="static/recap/DSC_9927.jpg" class="recap"/>
                <img src="static/recap/DSC_9932.jpg" class="recap"/>
                <img src="static/recap/DSC_0233.jpg" class="recap"/>
                <img src="static/recap/DSC_9821.jpg" class="recap"/>
                <img src="static/recap/DSC_0275.jpg" class="recap"/>
                <img src="static/recap/DSC_0005.jpg" class="recap"/>
                <img src="static/recap/DSC_0111.jpg" class="recap"/>
                <img src="static/recap/DSC_0260.jpg" class="recap"/>
                <img src="static/recap/DSC_9812.jpg" class="recap"/>
                <img src="static/recap/DSC_9900.jpg" class="recap"/>
                <img src="static/recap/DSC_9982.jpg" class="recap"/>
                <img src="static/recap/DSC_9929.jpg" class="recap"/>

                <img src="static/recap/DSC_0137.jpg" class="recap"/>
                <img src="static/recap/DSC_9950.jpg" class="recap"/>
                <img src="static/recap/DSC_9813.jpg" class="recap"/>
                <img src="static/recap/DSC_0025.jpg" class="recap"/>
                <img src="static/recap/DSC_9795.jpg" class="recap"/>
                <img src="static/recap/DSC_9876.jpg" class="recap"/>
                <img src="static/recap/DSC_0230.jpg" class="recap"/>
                <img src="static/recap/DSC_9905.jpg" class="recap"/>
                <img src="static/recap/DSC_0009.jpg" class="recap"/>
                <img src="static/recap/DSC_9948.jpg" class="recap"/>
                <img src="static/recap/DSC_0032.jpg" class="recap"/>
                <img src="static/recap/DSC_0227.jpg" class="recap"/>
                <img src="static/recap/DSC_9846.jpg" class="recap"/>
                <img src="static/recap/DSC_9783.jpg" class="recap"/>
                <img src="static/recap/DSC_9792.jpg" class="recap"/>
                <img src="static/recap/DSC_9938.jpg" class="recap"/>
                <img src="static/recap/DSC_0079.jpg" class="recap"/>
                <img src="static/recap/DSC_9995.jpg" class="recap"/>
                <img src="static/recap/DSC_9833.jpg" class="recap"/>
                <img src="static/recap/DSC_0012.jpg" class="recap"/>
                <img src="static/recap/DSC_0117.jpg" class="recap"/>
                <img src="static/recap/DSC_0131.jpg" class="recap"/>
                <img src="static/recap/DSC_0003.jpg" class="recap"/>
                <img src="static/recap/DSC_0013.jpg" class="recap"/>
                <img src="static/recap/DSC_0071.jpg" class="recap"/>
                <img src="static/recap/DSC_0156.jpg" class="recap"/>
                <img src="static/recap/DSC_9815.jpg" class="recap"/>
                <img src="static/recap/DSC_0150.jpg" class="recap"/>
                <img src="static/recap/DSC_0193.jpg" class="recap"/>
                <img src="static/recap/DSC_9921.jpg" class="recap"/>
                <img src="static/recap/DSC_0192.jpg" class="recap"/>
                <img src="static/recap/DSC_0049.jpg" class="recap"/>
                <img src="static/recap/DSC_0176.jpg" class="recap"/>
                <img src="static/recap/DSC_0199.jpg" class="recap"/>
                <img src="static/recap/DSC_0118.jpg" class="recap"/>
                <img src="static/recap/DSC_9962.jpg" class="recap"/>
                <img src="static/recap/DSC_0170.jpg" class="recap"/>
                <img src="static/recap/DSC_9836.jpg" class="recap"/>
                <img src="static/recap/DSC_0220.jpg" class="recap"/>
                <img src="static/recap/DSC_9934.jpg" class="recap"/>
                <img src="static/recap/DSC_9851.jpg" class="recap"/>
                <img src="static/recap/DSC_9969.jpg" class="recap"/>
                <img src="static/recap/DSC_0139.jpg" class="recap"/>
                <img src="static/recap/DSC_9925.jpg" class="recap"/>
                <img src="static/recap/DSC_0241.jpg" class="recap"/>
                <img src="static/recap/DSC_0166.jpg" class="recap"/>
                <img src="static/recap/DSC_9977.jpg" class="recap"/>
                <img src="static/recap/DSC_0222.jpg" class="recap"/>
                <img src="static/recap/DSC_9871.jpg" class="recap"/>
                <img src="static/recap/DSC_0232.jpg" class="recap"/>
                <img src="static/recap/DSC_0182.jpg" class="recap"/>
                <img src="static/recap/DSC_9993.jpg" class="recap"/>
                <img src="static/recap/DSC_9869.jpg" class="recap"/>
                <img src="static/recap/DSC_0165.jpg" class="recap"/>
                <img src="static/recap/DSC_0161.jpg" class="recap"/>
                <img src="static/recap/DSC_9879.jpg" class="recap"/>
                <img src="static/recap/DSC_0133.jpg" class="recap"/>            
            </div>
         </div>
    )
    
} )